# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AnimeCharacters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, role=None):  # noqa: E501
        """AnimeCharacters - a model defined in OpenAPI

        :param id: The id of this AnimeCharacters.  # noqa: E501
        :type id: str
        :param name: The name of this AnimeCharacters.  # noqa: E501
        :type name: str
        :param role: The role of this AnimeCharacters.  # noqa: E501
        :type role: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'role': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'role': 'role'
        }

        self._id = id
        self._name = name
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'AnimeCharacters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Anime_characters of this AnimeCharacters.  # noqa: E501
        :rtype: AnimeCharacters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this AnimeCharacters.


        :return: The id of this AnimeCharacters.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AnimeCharacters.


        :param id: The id of this AnimeCharacters.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AnimeCharacters.


        :return: The name of this AnimeCharacters.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AnimeCharacters.


        :param name: The name of this AnimeCharacters.
        :type name: str
        """

        self._name = name

    @property
    def role(self):
        """Gets the role of this AnimeCharacters.


        :return: The role of this AnimeCharacters.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this AnimeCharacters.


        :param role: The role of this AnimeCharacters.
        :type role: str
        """

        self._role = role
