# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CharacterActor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, picture=None):  # noqa: E501
        """CharacterActor - a model defined in OpenAPI

        :param id: The id of this CharacterActor.  # noqa: E501
        :type id: str
        :param name: The name of this CharacterActor.  # noqa: E501
        :type name: str
        :param picture: The picture of this CharacterActor.  # noqa: E501
        :type picture: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'picture': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'picture': 'picture'
        }

        self._id = id
        self._name = name
        self._picture = picture

    @classmethod
    def from_dict(cls, dikt) -> 'CharacterActor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Character_actor of this CharacterActor.  # noqa: E501
        :rtype: CharacterActor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CharacterActor.


        :return: The id of this CharacterActor.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CharacterActor.


        :param id: The id of this CharacterActor.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CharacterActor.


        :return: The name of this CharacterActor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CharacterActor.


        :param name: The name of this CharacterActor.
        :type name: str
        """

        self._name = name

    @property
    def picture(self):
        """Gets the picture of this CharacterActor.


        :return: The picture of this CharacterActor.
        :rtype: str
        """
        return self._picture

    @picture.setter
    def picture(self, picture):
        """Sets the picture of this CharacterActor.


        :param picture: The picture of this CharacterActor.
        :type picture: str
        """

        self._picture = picture
