# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnimeName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, english: str=None, romanji: str=None, native: str=None):  # noqa: E501
        """AnimeName - a model defined in Swagger

        :param english: The english of this AnimeName.  # noqa: E501
        :type english: str
        :param romanji: The romanji of this AnimeName.  # noqa: E501
        :type romanji: str
        :param native: The native of this AnimeName.  # noqa: E501
        :type native: str
        """
        self.swagger_types = {
            'english': str,
            'romanji': str,
            'native': str
        }

        self.attribute_map = {
            'english': 'english',
            'romanji': 'romanji',
            'native': 'native'
        }

        self._english = english
        self._romanji = romanji
        self._native = native

    @classmethod
    def from_dict(cls, dikt) -> 'AnimeName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Anime_name of this AnimeName.  # noqa: E501
        :rtype: AnimeName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def english(self) -> str:
        """Gets the english of this AnimeName.


        :return: The english of this AnimeName.
        :rtype: str
        """
        return self._english

    @english.setter
    def english(self, english: str):
        """Sets the english of this AnimeName.


        :param english: The english of this AnimeName.
        :type english: str
        """

        self._english = english

    @property
    def romanji(self) -> str:
        """Gets the romanji of this AnimeName.


        :return: The romanji of this AnimeName.
        :rtype: str
        """
        return self._romanji

    @romanji.setter
    def romanji(self, romanji: str):
        """Sets the romanji of this AnimeName.


        :param romanji: The romanji of this AnimeName.
        :type romanji: str
        """

        self._romanji = romanji

    @property
    def native(self) -> str:
        """Gets the native of this AnimeName.


        :return: The native of this AnimeName.
        :rtype: str
        """
        return self._native

    @native.setter
    def native(self, native: str):
        """Sets the native of this AnimeName.


        :param native: The native of this AnimeName.
        :type native: str
        """

        self._native = native
