# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.character import Character  # noqa: F401,E501
from swagger_server import util


class Movie(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, synopsis: str=None, directors: List[str]=None, writers: List[str]=None, duration: int=None, tags: List[str]=None, genres: List[str]=None, release_date: date=None, characters: List[Character]=None, rating: float=None):  # noqa: E501
        """Movie - a model defined in Swagger

        :param name: The name of this Movie.  # noqa: E501
        :type name: str
        :param synopsis: The synopsis of this Movie.  # noqa: E501
        :type synopsis: str
        :param directors: The directors of this Movie.  # noqa: E501
        :type directors: List[str]
        :param writers: The writers of this Movie.  # noqa: E501
        :type writers: List[str]
        :param duration: The duration of this Movie.  # noqa: E501
        :type duration: int
        :param tags: The tags of this Movie.  # noqa: E501
        :type tags: List[str]
        :param genres: The genres of this Movie.  # noqa: E501
        :type genres: List[str]
        :param release_date: The release_date of this Movie.  # noqa: E501
        :type release_date: date
        :param characters: The characters of this Movie.  # noqa: E501
        :type characters: List[Character]
        :param rating: The rating of this Movie.  # noqa: E501
        :type rating: float
        """
        self.swagger_types = {
            'name': str,
            'synopsis': str,
            'directors': List[str],
            'writers': List[str],
            'duration': int,
            'tags': List[str],
            'genres': List[str],
            'release_date': date,
            'characters': List[Character],
            'rating': float
        }

        self.attribute_map = {
            'name': 'name',
            'synopsis': 'synopsis',
            'directors': 'directors',
            'writers': 'writers',
            'duration': 'duration',
            'tags': 'tags',
            'genres': 'genres',
            'release_date': 'release_date',
            'characters': 'characters',
            'rating': 'rating'
        }

        self._name = name
        self._synopsis = synopsis
        self._directors = directors
        self._writers = writers
        self._duration = duration
        self._tags = tags
        self._genres = genres
        self._release_date = release_date
        self._characters = characters
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'Movie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Movie of this Movie.  # noqa: E501
        :rtype: Movie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Movie.


        :return: The name of this Movie.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Movie.


        :param name: The name of this Movie.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def synopsis(self) -> str:
        """Gets the synopsis of this Movie.

        Movie synopsis.  # noqa: E501

        :return: The synopsis of this Movie.
        :rtype: str
        """
        return self._synopsis

    @synopsis.setter
    def synopsis(self, synopsis: str):
        """Sets the synopsis of this Movie.

        Movie synopsis.  # noqa: E501

        :param synopsis: The synopsis of this Movie.
        :type synopsis: str
        """
        if synopsis is None:
            raise ValueError("Invalid value for `synopsis`, must not be `None`")  # noqa: E501

        self._synopsis = synopsis

    @property
    def directors(self) -> List[str]:
        """Gets the directors of this Movie.


        :return: The directors of this Movie.
        :rtype: List[str]
        """
        return self._directors

    @directors.setter
    def directors(self, directors: List[str]):
        """Sets the directors of this Movie.


        :param directors: The directors of this Movie.
        :type directors: List[str]
        """

        self._directors = directors

    @property
    def writers(self) -> List[str]:
        """Gets the writers of this Movie.


        :return: The writers of this Movie.
        :rtype: List[str]
        """
        return self._writers

    @writers.setter
    def writers(self, writers: List[str]):
        """Sets the writers of this Movie.


        :param writers: The writers of this Movie.
        :type writers: List[str]
        """

        self._writers = writers

    @property
    def duration(self) -> int:
        """Gets the duration of this Movie.

        Duration in minutes.  # noqa: E501

        :return: The duration of this Movie.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this Movie.

        Duration in minutes.  # noqa: E501

        :param duration: The duration of this Movie.
        :type duration: int
        """

        self._duration = duration

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this Movie.


        :return: The tags of this Movie.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this Movie.


        :param tags: The tags of this Movie.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def genres(self) -> List[str]:
        """Gets the genres of this Movie.


        :return: The genres of this Movie.
        :rtype: List[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[str]):
        """Sets the genres of this Movie.


        :param genres: The genres of this Movie.
        :type genres: List[str]
        """

        self._genres = genres

    @property
    def release_date(self) -> date:
        """Gets the release_date of this Movie.


        :return: The release_date of this Movie.
        :rtype: date
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: date):
        """Sets the release_date of this Movie.


        :param release_date: The release_date of this Movie.
        :type release_date: date
        """

        self._release_date = release_date

    @property
    def characters(self) -> List[Character]:
        """Gets the characters of this Movie.


        :return: The characters of this Movie.
        :rtype: List[Character]
        """
        return self._characters

    @characters.setter
    def characters(self, characters: List[Character]):
        """Sets the characters of this Movie.


        :param characters: The characters of this Movie.
        :type characters: List[Character]
        """

        self._characters = characters

    @property
    def rating(self) -> float:
        """Gets the rating of this Movie.

        Rating out of 100.  # noqa: E501

        :return: The rating of this Movie.
        :rtype: float
        """
        return self._rating

    @rating.setter
    def rating(self, rating: float):
        """Sets the rating of this Movie.

        Rating out of 100.  # noqa: E501

        :param rating: The rating of this Movie.
        :type rating: float
        """

        self._rating = rating
