#This is an example configuration file. 
#Copy this file and rename it to config.yaml.

#MongoDB connection
mongodb_host: "SQLContainer"
mongodb_port: 27017
mongodb_database: "test"

#If this is true, it will look for the credentials below.
mongodb_auth : "false"

#Credentials
mongodb_user: "test"
mongodb_password: "test123"
