openapi: 3.0.0
info:
  title: Spiral Media Tracker
  version: 0.1.0
  description: Testing API for Spiral Media Tracker
  termsOfService: 'https://spiral6.xyz/api/terms'
  contact:
    email: admin@spiral6.xyz
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://localhost/api'
paths:
  /anime:
    get:
      responses:
        '200':
          description: Operation successful.
      description: Return all anime.
      tags:
        - anime
      operationId: get_anime
      x-annotation-swagger-router-controller: swagger_server.controllers.anime_controller
    post:
      responses:
        '405':
          description: Invalid input.
      tags:
        - anime
      operationId: add_anime
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Anime'
        required: true
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.anime_controller
    put:
      responses:
        '404':
          description: Anime not found.
        '405':
          description: Validation exception.
      tags:
        - anime
      operationId: update_anime
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Anime'
        required: true
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.anime_controller
  '/anime/{ID}':
    get:
      responses:
        '200':
          description: Operation successful.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Anime'
        '404':
          description: Anime not found.
      description: Returns a single anime.
      tags:
        - anime
      operationId: get_anime_by_id
      parameters:
        - name: ID
          in: path
          required: true
          description: ID of anime to return.
          schema:
            type: number
      x-annotation-swagger-router-controller: swagger_server.controllers.anime_controller
    delete:
      responses:
        '404':
          description: Anime not found.
      description: ID of anime to delete.
      tags:
        - anime
      operationId: delete_anime
      parameters:
        - name: api_key
          in: header
          schema:
            type: string
        - name: ID
          in: path
          required: true
          description: ID of anime to delete.
          schema:
            type: number
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.anime_controller
  /movies:
    get:
      responses:
        '200':
          description: Operation successful.
      description: Return all movies.
      tags:
        - movies
      operationId: get_movies
      x-annotation-swagger-router-controller: swagger_server.controllers.movies_controller
    post:
      responses:
        '405':
          description: Invalid input.
      tags:
        - movies
      operationId: add_movie
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.movies_controller
    put:
      responses:
        '404':
          description: Movie not found.
        '405':
          description: Validation exception.
      tags:
        - movies
      operationId: update_movie
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.movies_controller
  '/movies/{ID}':
    get:
      responses:
        '200':
          description: Operation successful.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found.
      description: Returns a single movie.
      tags:
        - movies
      operationId: get_movie_by_name
      parameters:
        - name: ID
          in: path
          required: true
          description: ID of movie to return.
          schema:
            type: number
      x-annotation-swagger-router-controller: swagger_server.controllers.movies_controller
    delete:
      responses:
        '404':
          description: Movie not found.
      tags:
        - movies
      description: Deletes a single movie.
      operationId: delete_movie
      parameters:
        - name: api_key
          in: header
          schema:
            type: string
        - name: ID
          in: path
          required: true
          description: ID of movie to delete.
          schema:
            type: number
      security:
        - mediatracker_auth:
            - write
      x-annotation-swagger-router-controller: swagger_server.controllers.movies_controller
components:
  schemas:
    Character:
      example:
        actor: actor
        name: name
        picture: picture
        actor_picture: actor_picture
      type: object
      properties:
        name:
          type: string
        actor:
          type: string
        picture:
          type: string
        actor_picture:
          type: string
      required:
        - name
    Anime:
      xml:
        name: Anime
      example:
        id: 0
        studios:
          - Bones
          - Square Enix
        format: TV
        rating: 92
        synopsis: synopsis
        source: Manga
        tags:
          - tags
          - tags
        duration: 63
        characters:
          - actor: actor
            name: name
            picture: picture
            actor_picture: actor_picture
          - actor: actor
            name: name
            picture: picture
            actor_picture: actor_picture
        release_date: '2009-04-05'
        genres:
          - genres
          - genres
        name:
          romanji: 'Hagane no Renkinjutsushi: Fullmetal Alchemist'
          native: '鋼の錬金術師 FULLMETAL ALCHEMIST'
          english: 'Fullmetal Alchemist: Brotherhood'
        season: 'Spring 2009'
        episodes: 6
      type: object
      properties:
        id: 
          type: integer
        name:
          $ref: '#/components/schemas/AnimeName'
        format:
          description: Broadcast format of anime.
          enum:
            - ONA
            - OVA
            - TV
            - Movie
            - Special
            - Music
            - TV Short
          type: string
        tags:
          type: array
          items:
            type: string
        genres:
          type: array
          items:
            type: string
        synopsis:
          description: Anime synopsis.
          type: string
        season:
          type: string
        duration:
          description: Duration in minutes.
          type: integer
        release_date:
          type: string
          format: date
        studios:
          type: array
          items:
            type: string
        episodes:
          description: Number of episodes.
          type: integer
        source:
          description: Original source of anime.
          enum:
            - Original
            - Manga
            - Light Novel
            - Visual Novel
            - Novel
            - Video Game
            - Doujinshi
          type: string
        characters:
          type: array
          items:
            $ref: '#/components/schemas/Character'
        rating:
          description: Rating out of 100.
          type: number
          format: float
      required:
        - format
        - name
        - synopsis
    Movie:
      xml:
        name: Movie
      example:
        id: 0
        duration: 0
        characters:
          - actor: actor
            name: name
            picture: picture
            actor_picture: actor_picture
          - actor: actor
            name: name
            picture: picture
            actor_picture: actor_picture
        release_date: '2000-01-23'
        genres:
          - genres
          - genres
        directors:
          - directors
          - directors
        name: The Godfather
        rating: 6.0274563
        synopsis: synopsis
        writers:
          - writers
          - writers
        tags:
          - tags
          - tags
      type: object
      properties:
        id:
          type: integer
        name:
          example: The Godfather
          type: string
        synopsis:
          description: Movie synopsis.
          type: string
        directors:
          type: array
          items:
            type: string
        writers:
          type: array
          items:
            type: string
        duration:
          description: Duration in minutes.
          type: integer
        tags:
          type: array
          items:
            type: string
        genres:
          type: array
          items:
            type: string
        release_date:
          type: string
          format: date
        characters:
          type: array
          items:
            $ref: '#/components/schemas/Character'
        rating:
          description: Rating out of 100.
          type: number
          format: float
      required:
        - name
        - synopsis
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      required:
        - code
        - type
        - message
    AnimeName:
      example:
        romanji: 'Hagane no Renkinjutsushi: Fullmetal Alchemist'
        native: '鋼の錬金術師 FULLMETAL ALCHEMIST'
        english: 'Fullmetal Alchemist: Brotherhood'
      properties:
        english:
          example: 'Fullmetal Alchemist: Brotherhood'
          type: string
        romanji:
          example: 'Hagane no Renkinjutsushi: Fullmetal Alchemist'
          type: string
        native:
          example: '鋼の錬金術師 FULLMETAL ALCHEMIST'
          type: string
      required:
        - english
        - romanji
        - native
      type: object
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    mediatracker_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://spiral6.xyz/oauth/dialog'
          scopes:
            write: Modify items in database.
            read: Read items from database.
    api_key:
      type: apiKey
      in: header
      name: api_key
  links: {}
  callbacks: {}
externalDocs:
  url: 'http://spiral6.xyz/wiki/api'
  description: Documentation.
tags:
  - name: anime
    description: Anime items endpoint.
    externalDocs:
      url: 'http://spiral6.xyz/wiki/api/anime'
      description: Find out more
  - name: movies
    description: Movie items endpoint.
    externalDocs:
      url: 'http://spiral6.xyz/wiki/api/movies'
      description: Find out more
